// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyChXQ4VfTuhpWPjxIb9r-uMGlyWlalUfXQ',
    appId: '1:288161488521:web:ba65f7f3935059dba5b058',
    messagingSenderId: '288161488521',
    projectId: 'indolakto-project',
    authDomain: 'indolakto-project.firebaseapp.com',
    storageBucket: 'indolakto-project.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB1j7sLvWI2I8z_NWPGVorOoU_sFfUatag',
    appId: '1:288161488521:android:99dfa25a62eec5b8a5b058',
    messagingSenderId: '288161488521',
    projectId: 'indolakto-project',
    storageBucket: 'indolakto-project.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCtRGjCTleZmkTbDksogIDnU_JsXOtNuO4',
    appId: '1:288161488521:ios:2e8c8dff2dbead17a5b058',
    messagingSenderId: '288161488521',
    projectId: 'indolakto-project',
    storageBucket: 'indolakto-project.appspot.com',
    iosClientId: '288161488521-8dmnfu05sppndr86mk2lpmicvg5tdds5.apps.googleusercontent.com',
    iosBundleId: 'com.example.indlktProj',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCtRGjCTleZmkTbDksogIDnU_JsXOtNuO4',
    appId: '1:288161488521:ios:a9fe92962bf52fdda5b058',
    messagingSenderId: '288161488521',
    projectId: 'indolakto-project',
    storageBucket: 'indolakto-project.appspot.com',
    iosClientId: '288161488521-ctl4i7d9gjirppnmsiaempiu0bkng63f.apps.googleusercontent.com',
    iosBundleId: 'com.example.indlktProj.RunnerTests',
  );
}
